// Generated by IcedCoffeeScript 1.7.1-f
var transform;

transform = require('coffee-react-transform');

module.exports = function(content) {
  if (this.cacheable) {
    this.cacheable();
  }
  content = content.replace(/(<[^>]+)(class=)([^>]+>)/g, "$1className=$3");
  return transform("# @cjsx React.DOM\nReact = require('react')\nmodule.exports = ->\n" + (content.split('\n').map(function(l) {
    return '  ' + l;
  }).join('\n')));
};
