// Generated by CoffeeScript 1.7.1
(function() {
  var transform;

  transform = require('coffee-react-transform');

  module.exports = function(content) {
    if (this.cacheable) {
      this.cacheable();
    }
    content = content.replace(/(<[^>]+)(class=)([^>]+>)/g, "$1className=$3");
    return transform("# @cjsx React.DOM\nmodule.exports = ->\n" + (content.split('\n').map(function(l) {
      return '  ' + l;
    }).join('\n')));
  };

}).call(this);
